dist: trusty
sudo: false
language: node_js
services:
- docker
env:
  matrix:
  - CI=true
  global:
  - secure: lT2a6NTkncCu1Ktk2/1WfFvPuXnpxL/QSBB86GuGDVeXHV/1yl1WnZhfBrn7QgbT3VlkulMzuyZb8kkcZddLg9HkvX6qXdl+Ab9ijfjA3ZCknvq6XCqVGMRSemHvWCr05CF4bckS4ZdefVjVNyA8D7ywUyQMIYJ7XZVN8xiUE8OH4nP8s7Pu67gZlQBATWHRe7WF5mqCrz3Rgo5lWc5GS4RIJNe5mEk4SkLrjVEDn+XG7oBXqFU70eUISwRoDRIiijR535IqAwAmoPGda1MROqhYhMd18Mbg20GF9KArJ0YUgdFbHA/FubPCChr7iu1IXl7Y/WkXAzKux7b0R0m4WpU7nUhYLnA07IK+hMFKLtl8Tqto0m+jV50MGEKEI5OwMZzbyAv/jqgI5p0yXmlgjuDXLeGNHW6oyk6xZ+vH2begIDI6c44pc1rHwT3602MRuch1OZzMtzFv58J3t7rRMa2ZxK3xjJeLUY2ds4JpD7uRn2PJgSRN543qGeAxxATD5S2TeRVbxWXO3f38TlgPq/ovP7X4aleMF1lGavz/8vFkO/+xgLeuetIZ/S+4yICgdn0iHO0aeJ8xfvrF+lEWTxI7MuDlo8/1247q/y7orqGHeLOKf8K405q+lRlY9NCUMkxqn0S3EdWk5mpkDXC16GGCJYVLx0QOxGZizJghcg0=
  - secure: JciOfyXHAlyiq5II0A+cc6lM81xFDZj1eTUp2gbt8X/hzislpMJDkNoQRg8YBwhbHfR7LzJGWOlkyIHUZ71WtvNp2YN1r5kGx54d3EueHSGyCAmQTEjerU/u2dXwMmATR8WVfh2bQvRczLKv38joP2dkf5Rc+YphSiFIr1YDEprQOScGGRhLueFIKvLXDDWMuHqotR1G8wFfyW6qrs6ACHYEyuUxVpwnwLwOOC4uqIWbxa4ChCcwP0aodnWXPyQ8zyfpMYwnhNbupUylx0TeUmEGosGnkAob5BqaSY9abMM4yrRgnRhtJjSdT2OuBkhx9MvAcRLkaV9kxIhCfK1D9a6ZY8FQkhSp5xT8Nqh+5lcyG/xO/JfE9IuDoOC7h0vOi2kMaUPLmSPrhH10ZaEE2g/1yCu4EO+1X82P9h+9FVRsIierbgh3c3rfcKOuxqpWYKrWJzpAUo1NRgKI2OzKUr3lcmTYJyXcoIt7JDQjWwMydwYnAnUxb/7ebFweDBKIoxgs49TnP9CZ2TiTHDBdO3Qgf7lQgwdNfWRLXHlC+t3+d5lZlLMveXneCrJe8IBaHuVp2RweOSXFf02DYR1YCj9iL/D/MDa4syaKN0b2Y+jjCxRumdHGq5t0HLSEKdhHt8Qz1LSCIyR25T0UOOADvpqXyhopobMk+WRMt06+pkw=
  - secure: nspmaZe8CfVVwWgpxezLpCFDXqESHlgWJr1bXVvOeUu801P9Y1NxQKH6vpnlZLaMyZtW/eYownCFWN1JFv8X1EQybYtw3w8peY6pa9jI1Pkj1jhQmO30YDweynQHwlUKH2okgSk7uhwxzVIPqBWSeWGrbmW7fYYu/wjpHSKs43EmailMLacOR82LiseFc3QQN/0I71mXSRhz5nzIRn0DJY8ivXABSUixhHdhpP6y59mc6BLsasjImNC66mvvSFc4hs1BZGkm6cgvhPuDEyfRkKIlmiDNGeV7Vg4+KppSOT4R+55M5Xyj3jmJ7Yke9c0YMtKoLHOPZkABQ1BPmKTYRK06CEYRGz/UPV9Y6svZvq+CsnfOusNIw4/ZYEjFTiXUeYEva+K0/0zADDOM4hWgJB/gGt0A46xuSilK4puwT2P6WxZXuZwH4YWadlcLiRefzPebB2DpRW38eg6SYOn9h7ns09w8CilHUEg+9FyXBS/BM52NuFJuuSru1tvmHS2wBlxmCw/ieUHOD7Y9mRP8JGzZ37pwOYSjpDKjB0v8mmz3Y0t5gMEBHYXKXUZMuOgVFNydt9L8jbZ+y0WrtbP/ZgFyJOEbJuIRHPkx3XJr3GkzL56JhlFEvDADnq3JQK1twhJOzIgjsryLOy1N9R9XzeQTnzfujkjZRDhM/h3MPV0=
  - secure: Jd/UarbYG4MfqMRMV8cuzia6ImYSckar5z01bmVg2TtFEhZRwZbljDfKCurRjenXDVKC2+7UV5PXz3PDj1y9bkVYeJB5a46f3fQL8yOxXJwPTrt0muq0Wvxv+gyqfQQWnbH/niIbVoqg9VFqgapK1GY/Bbgpgp/iAj+iwb4V44+XAVvCqKQaR4RPamaZzt/l+a6M3KzylpzChc+JYutmxzEw8asWhZDH5o3g27nMBScuhQc/fwmLGKIT0XUkr/pZXME5tdO7jDBEkSqq62EE/UjTsQMoSvb3CG/4FIi+T/gZ5Aqre3qDENz2ofAdFtJviTLvih6XJvj+/ZLYbi9YIP0RbqJo75MbGzlWIBPNQ4NMtnskFvMOfHJ6xgbqtgayNGrb2vbr2FITMq5YbDKKkpibsl45ijkLi9AaoxBV5KePFmA/YyDUGOBBdFWv53zFXTzaV5vJO6JwLaSL8Wysz1EHVHkRhJLaODQxAVujnW9kzrHNOlE7EOrVg03xWTfBMZ7ISBv2hPNmj8Xt6bBW/t5+hg8M5GUt5TDWecz7f50IgYsL28usUvAm/U7K0y82S6ushU3scRqbNOzq7Igv+/1TcIlrhk9onrVYAuMETpplxU3wki8RaZmTDAELCopur1ZhWDqUil73fDBWQlKWgRP6ODi4knk76mHrYJFDiJk=
  - secure: U5x0Th4ymP8dE/OyLVqmzhtQnAT7oLIYtVXUN7wOTCbFEhcHsW0dkUvHPVT2HvKnhZiV9Bt8Xf6WzVPTrTVU3DySPjvc8+2YO0z6/j3B07ZNClv40kvAgETz5crUf4vlFMEALpWgTvqnC1UiNgm13m0yp+a4NBS16RJVo+7OCd4xlZ6eQgXmkAmeoSuGLQcXQpbYi3fzpBqKoPtT2PsvVXvvGtNleqh4ZaNDmIkb2sJm6aLLow0HlWlZSzkFMzmzLqzrfeoGnqe/nks5iIQwpSgWcnTVwIscKKB+o2VukINWg9cPvMQRhMyxot4iMsA6Q/RGoN5BwoHR7BkK+OpocrQ4XAdz1kagftz1AXvCHpBq7JAOsND7fGYhhO9YlAq2P4dzcOxlm0AFx9ONGCfu3WMzGd8Gl0oGxDMOrGIxgZGOV7oEIV+/UAIQltzgelyGJY20W/C3e+KBBJCZYDWJU/P3Yifej5AJV3q+hcE7baDC2qPb7BEunprb9puAZXBATt3RtEXsS/ceMJrNn9AOAZRb+cmEW0ulEMMxccoMfw+h3clvPuwxW9JNFoqCeGkI48+9j0TDcqTJxgXMfxM2CSQwLOTOWym32r2Dywe+p/5rYQVJiT8Cb/pqJ+CG2fFrEIL2RCZbDdn17vTYFf4ZVj+EMkehdqHMpVurdtt3M8E=
  - secure: ByPgIAx1JIamM6AMQvfrvyLddDwkO4cnGHOBLQMTLzYVPUQ2tsP0mYnlRyXv05FCUFRvC5jsMmLk0B/llHf51BNdH1aYphmt/YqczocGIt0X3iOGYZb+Fp2cIxv4te4zFEXbf5sz2JOurS7C5x2Pokm0yvy3EWGKCJA3DLJXSbJ0+vHSgKRvOnD8tsfZxlhy5AQjPsCPYYRy2gKoFH9hehbCELkYtcBCLGFj8wmRF3KrInXivHOxZ/1uN4+uIvLnGthJk7n/26SrxndD+XrI+4R5dQnv89iKwWiR5qCBVBZ1GJVpP9byFiWngok0VQhpljysTOYxk22D6U948X8qfSbshZWn2qHKJuziNL0dwkp0RJBQtxw+F6CAgftrrmA9KqlcWdGhlwHcxxssC8+QsSC8PqqmbND9EPRllMa1CHStX0rLm4V8qst1oXybaPR90RKFsM8p/b45tFfBXzppHD/lGUXaYrz/WeH+Axaft64TlUChil2zkbqafK/9m3jJOb8RWc19Ell3O4e7YoGPq+PsI/motxrFQ+xcYsdEw+QwgtrngT/L1dCCzgYO2nK+iA8+hxMXn1tFYU86wA3obduDEuCbo/3bnv9TiUvMbzoh2gg+o7O99KkKqvgMSX7ZBaf/pp+11d3K4ThaRdF4NZoLX0OEXtxr6W+TqqX85rQ=
  - secure: nTwAdaXM0RCxpWOZIOCJS4qEXtE9S5kp3qVZDHWvEI7AUCGm7dWZZc0EowCF+UCP/fpz8wZXPTw7hu3h/dX5AGWnU7MrDMWJOqxg8W7ElmXKIdU6hWDboBniAkzqdbjOPxF43hGHYqQ8H1toEMb75zseGBVIwITRG0vPv3j230wM65hkPTij/cqRus8pKcOxlTmZJmfNhqNoV4U+IC/bvNjyCVlnIKsMYbIeR7sIWOButGpHv7wynUZh/rWt7nMthBfcS6V7ft0ETRt+pcFjz7Xea0OkKmp51YePB33wOt2RyHALyjALxBjgO+Yc3LZzGfG9W+6l4zU0boFus0yBPcnyBkCHqeOUVXG2GimgYX3W2D9jXNdxYXR7zyFKxgv+d9gXOzETL8bM41M/P2h2Yk6t/aPq13w/oB7qOfbV6gyJ4B4idemh44emayOSgLzGp0iy1xyfE/dnC4Iub0++2nVi0vmdRIzh9QbChdDDha6yljobRUOgqOMm5kfPwKNTYy43l1YhtvxdNojVKV02CHNRYvk19XnamSRcUM6EbeGAhkTnO0rkKVVqKFl31iwr7UW0BIota7vApH0UbwxF13DEak3096o8pRX0C95DX0A6UJdajUBk3JtCUJoilRQhdrIdM6I4oDGOPlohStF+daP146L0iLcG7v79vDaV9Hg=
node_js:
- 12.9.0
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_success:
- export COMMIT=${TRAVIS_COMMIT::7}
- export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG";else echo "$TRAVIS_BRANCH--$COMMIT";
  fi`
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose build
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- docker tag $TEST_IMAGE_NAME:latest $TEST_IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
- docker push $TEST_IMAGE_NAME
before_deploy:
- npm install netlify-cli -g
- npm run build -- --configuration=test
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./dist/client --prod
  skip_cleanup: true
  on:
    branch: master
