dist: trusty
sudo: false
language: node_js
services:
- docker
env:
  matrix:
  - CI=true
  global:
  - secure: lT2a6NTkncCu1Ktk2/1WfFvPuXnpxL/QSBB86GuGDVeXHV/1yl1WnZhfBrn7QgbT3VlkulMzuyZb8kkcZddLg9HkvX6qXdl+Ab9ijfjA3ZCknvq6XCqVGMRSemHvWCr05CF4bckS4ZdefVjVNyA8D7ywUyQMIYJ7XZVN8xiUE8OH4nP8s7Pu67gZlQBATWHRe7WF5mqCrz3Rgo5lWc5GS4RIJNe5mEk4SkLrjVEDn+XG7oBXqFU70eUISwRoDRIiijR535IqAwAmoPGda1MROqhYhMd18Mbg20GF9KArJ0YUgdFbHA/FubPCChr7iu1IXl7Y/WkXAzKux7b0R0m4WpU7nUhYLnA07IK+hMFKLtl8Tqto0m+jV50MGEKEI5OwMZzbyAv/jqgI5p0yXmlgjuDXLeGNHW6oyk6xZ+vH2begIDI6c44pc1rHwT3602MRuch1OZzMtzFv58J3t7rRMa2ZxK3xjJeLUY2ds4JpD7uRn2PJgSRN543qGeAxxATD5S2TeRVbxWXO3f38TlgPq/ovP7X4aleMF1lGavz/8vFkO/+xgLeuetIZ/S+4yICgdn0iHO0aeJ8xfvrF+lEWTxI7MuDlo8/1247q/y7orqGHeLOKf8K405q+lRlY9NCUMkxqn0S3EdWk5mpkDXC16GGCJYVLx0QOxGZizJghcg0=
  - secure: JciOfyXHAlyiq5II0A+cc6lM81xFDZj1eTUp2gbt8X/hzislpMJDkNoQRg8YBwhbHfR7LzJGWOlkyIHUZ71WtvNp2YN1r5kGx54d3EueHSGyCAmQTEjerU/u2dXwMmATR8WVfh2bQvRczLKv38joP2dkf5Rc+YphSiFIr1YDEprQOScGGRhLueFIKvLXDDWMuHqotR1G8wFfyW6qrs6ACHYEyuUxVpwnwLwOOC4uqIWbxa4ChCcwP0aodnWXPyQ8zyfpMYwnhNbupUylx0TeUmEGosGnkAob5BqaSY9abMM4yrRgnRhtJjSdT2OuBkhx9MvAcRLkaV9kxIhCfK1D9a6ZY8FQkhSp5xT8Nqh+5lcyG/xO/JfE9IuDoOC7h0vOi2kMaUPLmSPrhH10ZaEE2g/1yCu4EO+1X82P9h+9FVRsIierbgh3c3rfcKOuxqpWYKrWJzpAUo1NRgKI2OzKUr3lcmTYJyXcoIt7JDQjWwMydwYnAnUxb/7ebFweDBKIoxgs49TnP9CZ2TiTHDBdO3Qgf7lQgwdNfWRLXHlC+t3+d5lZlLMveXneCrJe8IBaHuVp2RweOSXFf02DYR1YCj9iL/D/MDa4syaKN0b2Y+jjCxRumdHGq5t0HLSEKdhHt8Qz1LSCIyR25T0UOOADvpqXyhopobMk+WRMt06+pkw=
  - secure: Hamdjb3FI2JIiB40W6tt7dhTInnwbyhUI0Mq6Y/4QVDdNsxapQQHZzKi+n12TlDO3d6uQTGTwlcOuthJz4REoBMdbrZxDxOMNt6UD01hyVZndPPbKXeIF4nni7wucm19K+OO7IIkEu06jHnFDH4S2bKmFEvyInOYTof8t/8Pmb9cbGHdN8rxSCxF7CRrxKHkkVLMwluHhjToubqDlLln2lDQ+CFgAIIRTWdcK6Vpf5bnjrL0gXxWkO5dRHtmWKBDpiUv5azlQMFdtpoPAw0IyDtpiK7g17dlL6+jj4ut3rSFhkTH/hMpL0I5n3l9IH0toPePP31IIXsFTfVdQaizL0rL5n7YoP8TzqDYiGoQVCdQzRjzn0m9W/g3DV9WL1gOKxHt+LQe/Iv/9+HJJFMrJKNhym1crUpzmeKnn21TD2cCiwcJISJtX6xsUM6EaNaqni4gc2ocCIDMqug3qlw+u53EJkZrRCaWeVPDuDrPLLpkkhthwg1U5U4I8vdj9ndwywHH6fSaey0pF3s+SIRvB7gH61JnnoGRr3wWd6+4GKJtu1SIpdRlii3wUyrkXaxDEj7NpIOKg69LTFHrdrYeRKJ005r5g6QTMia8yjkGKPP4e3T+rRGtMhlR/ABG9pZxskiSN/dfgxiz12nB4MrKDNClzl7eO/gCpXaz83fkZ0E=
  - secure: lxtkpgMUUG6tLZf1jnbIYtJNP1qSDD8uBBtNowtRunM+SWrKwCPxdy+MtcsAtRJSLcgOJXldVtaLRyuh/SHHZ94DbdIALvCIM0CFN5S2UqB7nL7i9/kc9/R4gczZGZ+zbY5b7DwihZaSnOUtyKmd2zysaUur6y/9hLQITO05sEYuPgDj13G9n7qwMiJDnbcmNDFuOqbjfujJ9d2an0n5BSLfeU8bYTcyPmU+Xx2rQy7LYjv4PttEVkRZRAljfk/4eb+O6u7UJ9ZLjtX87b78g2Gl3C31ffyJYJLMgP053uNl7yX/EK79FJATOvZIuKoYkSGkJ9UEEhWaBEhUyewOPayJF/voo0r0c5Z/mrJl17v31FGxc9SCUwbQczOf2YSsQ+tx2IuLDVURWeNap/yFOCHU8xAQF+Fq98wx5dWSVnlYH0Cpttpz+dVBNhPO+0itEZmsHzamlMRmSHh0jr8ZLxDGA1xhyaUnQnD2S1HXXfsfbPibX/ztGczK8Y2QLCYFKRpMtInlHfp0t+6GeJZXR4rqxOZAOo6//SX68GYwHXuy3qzCbQjVrl12XFG3j6YBlRgDUAa1+gu++muCVPPb18li3Ia8tkgv3w0GDHbTarechRr5dk/6wzGKJQNUKYoc8F46KVoDJ1JRoW1RiRfpzE6uZIOKJn9AMvVLRtrgp9g=
  - secure: fl9TfnUzyxynAFeU5cO1AY8zfzgZ+NHj1u3teeifN2jJ8LB0zWQnkzrV6N6vdiHraa31gE/WlL8uPk4EB+hFjFz7cpgDRqUCzQSk/aYF7RvC131fS5B8cnQs1GmRZaeESrinRwqkfDnNmKI62mIigiFvD4yIZ0e4PODVlS2sT17fZ7PxFJ2wvgy/8sT+AQDo53fCURjwWTQi4KJa2Qix14cyVpf000IWPp4CNrJbLcOcijxUxPo7LNesrPg0OBpxf5JT+4L7uiTUuLeXHsOWBksFhmNVlReb7gJhuq0sU6J0GGumlxVZoJkt/ykmc6XOfyGG41aPw645Fzi+5XYPklungRQ8/kraq+euNFfJ6t6NWbopF+BmGVGjqnufLa35WjjOI8ch0qsAAt5FQkZ1qfR3bjOm2Lsl7vpgzahx/CeWNlkTUUBCveZY9jJf90Z5vw3PinvHE765quVkN68CbPXz9ttu+ItIk90/StGj4ORCOwqPSJgVYFlSCYPB1YmhZQvbj+1BaWC6ijJ8vHZmhOF9vUzNEf4U6fTwRCPQQJUrRKXlRPHlyP9ArO3xyF3pBnRvdWU0qPfEMUmgrv4aBc9ohRodrqoxp7RdXWnZ+sEzI5HdQ6zSCrEjHZks76ry9LCMiHdbyWBvX5yE2NjgWGMsY9qGUyQSqtSw/RCPpgg=
  - secure: IW+X+bXbVmhxAT+M/3AW4RDoHWTDi1tUUTkMbh5TpI0LlwvM9qs3UAxASppJ8DSLcUtI3vx3qW2QsfLi3qma3tFgdxSbKaGv81fMeWHWdWaIy0sIr4AQnZTIUWtukx6qNciMtp0wuHDXku/1C266Vg6xh1+XNHF4yeiYDZSBb97MQ5joVdj1/bbiDTc190kKz+2ls2EE9IGq7lDCFkefq9pPbLb5oQXTafB8B+2TmhDtk8mEU9RBM6svw58blM7lbTP5CVv8+w94BQD1zP1xqTx6ksbdKcQ8v3zn2PE1925M5aOd6Sp9axYtXbqBioPyNTmzirZ/VSOfdXrcOiLpGa4/yv4FLR0eTFZDmr/28INOV8XGr5ZK8eP8rg093irqh/G6eCIqa6vDbPyPFJHRRiyp4EqjewLyuN5WeBRAsV3hQMWZFOgkHBji/hjF4XZos/nXnQgwP8FocqzLUE0cTxA5lIlYxG+jPqQri9BtLP0RQr/QZK/RG2hzahoHJVgTYaeecM9SkBTKoEXcRTN+hySv+qTAmLZ/javByrs1j7jGRIkbkflNI0f/nHvkMnDUyEWjMWqOye3e9mlm2UR2XtTEXdU7x5vSZWqsXwFHdnsIlmt5JWpcAhqB7wNSBYWZjO3slKOEijVVTNu8SRLQ0GWBUA0hGSKzr1/WMpor67g=
node_js:
- 12.9.0
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
jobs:
  include:
    - stage: unit_tests
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - stage: build_docker_images
      script:
      - export COMMIT=${TRAVIS_COMMIT::7}
      - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG";else echo "$TRAVIS_BRANCH--$COMMIT";
        fi`
      - docker-compose build
      - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
      - docker-compose --file docker-compose-test.yml build
      - docker tag $TEST_IMAGE_NAME:latest $TEST_IMAGE_NAME:$TAG
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - docker push $IMAGE_NAME
      - docker push $TEST_IMAGE_NAME
    - stage: deploy_to_test_environment
      before_deploy:
      - npm install netlify-cli -g
      - npm run build -- --configuration=test
      deploy:
        provider: script
        script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./dist/client
        --prod
      skip_cleanup: true
      on:
      branch: master
