version: '3'
services:
  splitspends-ui:
    image: nagasagar/splitspends-ui:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
